#Datasource config information
wg:
  datasource:
    ip: 127.0.0.1
    username: root
    password: my-secret-pw
  auth-issuer: http://localhost:8090/api-uaa/


logging:
  level:
    ROOT: INFO

spring:
  jpa:
    show-sql: true

eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://user:password@localhost:8762/eureka
  instance:
    hostname: localhost
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}



