#Datasource config information
wg:
  datasource:
    ip: ${WG_DATABASE_IP}
    username: ${WG_DATABASE_USERNAME}
    password: ${WG_DATABASE_PASSWORD}
  auth-issuer: ${WG_DOMAIN_NAME}/api-uaa/


logging:
  level:
    ROOT: INFO

spring:
  jpa:
    show-sql: true

eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://user:password@wg-eureka:8762/eureka
  instance:
    hostname: localhost
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}



