server:
  port: 8762

spring:
  security:
    user:
      password: password
      name: user
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://user:password@localhost:8762/eureka
  server:
    enable-self-preservation: true
    renewal-percent-threshold: 0.45