management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    beans:
      enabled: true

server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: auth
          uri: lb://wg-uaa
          predicates:
            - Path=/api-uaa/**
          filters:
            - StripPrefix=1
            - PreserveHostHeader
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                redis-rate-limiter.requestedTokens: 1
        - id: user
          uri: lb://wg-usercenter
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
            - PreserveHostHeader

wg:
  client_id: user-service
  client_secret: password