server:
  port: 8100

spring:
  datasource:
    url: jdbc:mysql://${wg.datasource.ip}:3306/wg-db
    username: ${wg.datasource.username}
    password: ${wg.datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver


encrypt:
  key-store:
    location: classpath:mykeystore.jks
    alias: mykey
    password: password

security:
  oauth2:
    client:
      clientId: user-service
      clientSecret: password
      accessTokenUri: ${wg.auth-issuer}oauth/token
      grant-type: client_credentials
      scope: server

ribbon:
  ReadTimeout: 5002
  ConnectTimeout: 5000
  MaxAutoRetries: 0