spring:
  datasource:
    url: jdbc:mysql://${wg.datasource.ip}:3306/wg-db
    username: ${wg.datasource.username}
    password: ${wg.datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${wg.auth-issuer}
          jwk-set-uri: ${wg.auth-issuer}.well-known/jwks.json
server:
  port: 8200

eureka:
  instance:
    hostname: {WG_HOST_NAME}