spring:
  application:
    name: wg-config-server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
  profiles:
    active: native
  security:
    user:
      password: password
server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: '*'
