spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wg-db
    username: root
    password: my-secret-pw
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
logging:
  level:
    ROOT: DEBUG
wg:
  auth-issuer: http://localhost:${server.port}