spring:
  datasource:
    url: jdbc:mysql://${wg.datasource.ip}:3306/wg-db
    username: ${wg.datasource.username}
    password: ${wg.datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
logging:
  level:
    ROOT: INFO
wg:
  auth-issuer: http://localhost:${server.port}
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://user:password@localhost:8762/eureka
  instance:
    hostname: localhost
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}

encrypt:
  key-store:
    location: classpath:mykeystore.jks
    alias: mykey
    password: password

