version: "3.7"
services: 
  wg-config:
    image: wg-config:1.0
    environment: 
      WG_DOMAIN_NAME: ""
      WG_CONFIG_URL: http://wg-config:8888
  wg-eureka:
    image: wg-eureka:1.0
    depends_on: 
      - wg-config
    restart: on-failure
    ports: 
      - 8762:8762
    environment: 
      WG_CONFIG_URL: http://wg-config:8888
      WG_DOMAIN_NAME: "http://wg-gateway:8080"
  # wg-uaa:
  #   image: wg-uaa:1.0
  #   environment: 
  #     WG_CONFIG_URL: http://wg-config:8888
  #     WG_DOMAIN_NAME: "http://wg-gateway:8080"
  #     WG_DATABASE_IP: wg-sql
  #     WG_DATABASE_USERNAME: root
  #     WG_DATABASE_PASSWORD: password
  # wg-sql:
  #   image: mysql:8.0.19
  #   environment: 
  #    MYSQL_ROOT_PASSWORD: password
  # wg-reids:
  #   image: redis:6.0-rc
