spring:
  application:
    name: wg-eureka
  security:
    user:
      password: password
      name: user

server:
  port: 8762
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://user:password@localhost:8762/eureka
  server:
    enable-self-preservation: true
    renewal-percent-threshold: 0.45
