spring:
  datasource:
    url: jdbc:mysql://${wg.datasource.ip}:3306/wg-db
    username: ${wg.datasource.username}
    password: ${wg.datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8090/api-uaa/
          jwk-set-uri: http://localhost:8090/api-uaa/.well-known/jwks.json

logging:
  level:
    ROOT: DEBUG


#eureka client setup
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://user:password@localhost:8762/eureka
  instance:
    hostname: localhost
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
